spring:
    aot:
        enabled: true  # AOT (Ahead Of Time) 컴파일 활성화
    r2dbc:
        url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
#        url: r2dbc:postgresql://localhost:5432/test?loggerLevel=OFF
#        username: ${testcontainers.postgresql.username}
#        password: ${testcontainers.postgresql.password}
    sql:
        init:
            schema-locations: classpath:data/schema.sql
            mode: always
